# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: jacoco-badge-generator
      # You may pin to the exact commit or the version.
      # uses: cicirello/jacoco-badge-generator@ecfc9b09fd4061f58e58bc40372a5c0dc0efea96
        uses: cicirello/jacoco-badge-generator@v2.1.1
        #with:
          # Full path, relative to the root of the repository, to the jacoco csv file(s), including filename(s)
          #jacoco-csv-file: # optional, default is target/site/jacoco/jacoco.csv
          # The directory for storing badges, relative to the root of the repository.
          #badges-directory: # optional, default is .github/badges
          # The filename of the coverage badge.
          #coverage-badge-filename: # optional, default is jacoco.svg
          # The filename of the branches coverage badge.
          #branches-badge-filename: # optional, default is branches.svg
          # Controls whether or not to generate the coverage badge.
          #generate-coverage-badge: # optional, default is true
          # Controls whether or not to generate the branches coverage badge.
          #generate-branches-badge: # optional
          # Controls what happens if one or more jacoco.csv files do not exist.
          #on-missing-report: # optional, default is fail
